### ISSUE TITLE
default config file /etc/bunbun.yaml usually not redable

### ISSUE THREAD

**Issue by zdenek-crha** [edward-shen/bunbun#2]
I've decided to try bunbun after reading about it on reddit. I've followed installation notes from `README.md` just to be rewarded by error:

```
$ cargo install bunbun
... snip ...
   Installed package `bunbun v0.6.2` (executable `bunbun`)
$ bunbun
2020-06-26 11:01:16,150 ERROR [bunbun::config] Failed to write to /etc/bunbun.yaml: Permission denied (os error 13). Default config will be loaded but not saved.
2020-06-26 11:01:16,150 WARN  [bunbun] Couldn't watch /etc/bunbun.yaml: No such file or directory (os error 2). Changes to this file won't be seen!
Error: IoError(Os { code: 98, kind: AddrInUse, message: "Address already in use" })
```
I understand where the erorr comes from and what I need to do about resolving it. But I think it would be better to choose different default than `/etc/bunbun.yaml`. Most people would not be trying `bunbun` under `root` user and using `$HOME/.bunbun.yaml` would be more sensible.

Another option would be to check list of locations like:

- `/etc/bunbun.yaml
- `$XDG_CONFIG/bunbun.yaml` 
- `$HOME/bunbun.yaml` 

and settle for first one that exists and is readable. If none is found, it could choose first path into which it has write access and generate default configuration (and print it for user to see). 

In my opinion, if user executes `bunbun` just to see errors, it does not make a good first impression.

**Comment by edward-shen** [comment]
Hmmm thanks for the heads-up! You're right about that being a bad user experience, and I really like your suggestion. 

I'll implement it myself when I get a chance to, but I'd also welcome a PR!

Thanks for filing this out, I really appreciate the time and effort to do so!

**Comment by zdenek-crha** [comment]
Thanks for response. I probably won't be able to send PR as I'm quite busy on my own project. But I like idea behind `bunbun` and I tried to contribute at least by providing feedback

**Comment by edward-shen** [comment]
Hey, just a heads-up: version 0.7.0 addresses this issue. Thanks again for bringing it up!
